from enum import Enum


class SourceType(str, Enum):
    USER_ENTERED = "USER_ENTERED"
    PILOT_OBSERVED = "PILOT_OBSERVED"
    GOVERNMENT = "GOVERNMENT"
    MARKET_PROVIDER = "MARKET_PROVIDER"
    DERIVED = "DERIVED"
    ESTIMATED = "ESTIMATED"
    MOCK_DEMO = "MOCK_DEMO"
    LEGACY_UNKNOWN = "LEGACY_UNKNOWN"


class EvidenceType(str, Enum):
    MARKET_PRICE = "MARKET_PRICE"
    WEATHER_OBSERVATION = "WEATHER_OBSERVATION"
    WEATHER_WARNING = "WEATHER_WARNING"
    DISTRICT_STATISTIC = "DISTRICT_STATISTIC"
    BUSINESS_CONTEXT = "BUSINESS_CONTEXT"
    LEGACY_UNKNOWN = "LEGACY_UNKNOWN"


class ProviderStatus(str, Enum):
    SUCCESS = "SUCCESS"
    NO_DATA = "NO_DATA"
    TIMEOUT = "TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"


class FreshnessStatus(str, Enum):
    VERIFIED_FRESH = "VERIFIED_FRESH"
    VERIFIED_STALE = "VERIFIED_STALE"
    UNKNOWN = "UNKNOWN"


class ProviderMode(str, Enum):
    MOCK = "MOCK"
    LIVE = "LIVE"
