"""Phase 2 P1 offline scheme distribution

Revision ID: 2aa7bd5ebb52
Revises: 9f9307fedd66
Create Date: 2026-09-22 23:27:25.592646

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa7bd5ebb52'
down_revision: Union[str, None] = '9f9307fedd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_assessments', sa.Column('scheme_rule_version', sa.Integer(), nullable=True))
    op.add_column('finance_assessments', sa.Column('scheme_last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('locations', sa.Column('location_type', sa.String(length=30), nullable=True))
    op.add_column('scheme_rules', sa.Column('rule_version', sa.Integer(), nullable=False))
    op.add_column('scheme_rules', sa.Column('moratorium_interest_method', sa.String(length=30), nullable=False))
    op.add_column('scheme_rules', sa.Column('location_type', sa.String(length=30), nullable=True))
    op.add_column('scheme_rules', sa.Column('allowed_business_categories', sa.Text(), nullable=True))
    op.add_column('scheme_rules', sa.Column('source_name', sa.String(length=300), nullable=True))
    op.add_column('scheme_rules', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('scheme_rules', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schemes', sa.Column('official_source_name', sa.String(length=300), nullable=True))
    op.add_column('schemes', sa.Column('official_source_url', sa.String(length=500), nullable=True))
    op.add_column('schemes', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'last_verified_at')
    op.drop_column('schemes', 'official_source_url')
    op.drop_column('schemes', 'official_source_name')
    op.drop_column('scheme_rules', 'last_verified_at')
    op.drop_column('scheme_rules', 'source_url')
    op.drop_column('scheme_rules', 'source_name')
    op.drop_column('scheme_rules', 'allowed_business_categories')
    op.drop_column('scheme_rules', 'location_type')
    op.drop_column('scheme_rules', 'moratorium_interest_method')
    op.drop_column('scheme_rules', 'rule_version')
    op.drop_column('locations', 'location_type')
    op.drop_column('finance_assessments', 'scheme_last_verified_at')
    op.drop_column('finance_assessments', 'scheme_rule_version')
    # ### end Alembic commands ###
