"""P2 Closure: Fix Nullability and Provenance

Revision ID: 669388b27543
Revises: c78f1a2b3c4d
Create Date: 2026-09-23 15:25:11.079658

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '669388b27543'
down_revision: Union[str, None] = 'c78f1a2b3c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_models')
    op.alter_column('decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('evidence', 'parent_evidence_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.alter_column('evidence', 'raw_reference',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.add_column('finance_assessments', sa.Column('engine_version', sa.String(length=50), nullable=True))
    op.alter_column('finance_assessments', 'project_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'margin_contribution',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'maximum_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'recommended_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'total_tenure_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_assessments', 'active_repayment_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_assessments', 'capitalized_principal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'emi',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'total_interest',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'policy_version',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('stress_test_scenarios', 'break_even',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('stress_test_scenarios', 'resilience_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.add_column('sync_requests', sa.Column('payload_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_requests', 'payload_hash')
    op.alter_column('stress_test_scenarios', 'resilience_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('stress_test_scenarios', 'break_even',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'policy_version',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('finance_assessments', 'total_interest',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'emi',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'capitalized_principal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'active_repayment_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('finance_assessments', 'total_tenure_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('finance_assessments', 'annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'recommended_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'maximum_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'margin_contribution',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'project_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.drop_column('finance_assessments', 'engine_version')
    op.alter_column('evidence', 'raw_reference',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('evidence', 'parent_evidence_ids',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.create_table('dummy_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('test_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('test_decimal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('test_null', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dummy_models_pkey')
    )
    # ### end Alembic commands ###
