"""P2 Closure: Fix Nullability and Provenance

Revision ID: 669388b27543
Revises: c78f1a2b3c4d
Create Date: 2026-09-23 15:25:11.079658

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '669388b27543'
down_revision: Union[str, None] = 'c78f1a2b3c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('evidence', 'parent_evidence_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.alter_column('evidence', 'raw_reference',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=True)
    op.add_column('finance_assessments', sa.Column('engine_version', sa.String(length=50), nullable=True))
    op.alter_column('finance_assessments', 'project_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'margin_contribution',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'maximum_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'recommended_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'total_tenure_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_assessments', 'active_repayment_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_assessments', 'capitalized_principal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'emi',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'total_interest',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'working_capital_requirement',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('finance_assessments', 'policy_version',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('stress_test_scenarios', 'break_even',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.add_column('stress_test_scenarios', sa.Column('break_even_status', sa.String(length=50), nullable=True))
    op.alter_column('stress_test_scenarios', 'resilience_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.add_column('sync_requests', sa.Column('payload_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_requests', 'payload_hash')
    
    # Pre-downgrade cleanup to safely restore NOT NULL constraints
    op.execute("UPDATE stress_test_scenarios SET resilience_score = 0 WHERE resilience_score IS NULL")
    op.execute("UPDATE stress_test_scenarios SET break_even = 0 WHERE break_even IS NULL")
    op.execute("UPDATE finance_assessments SET working_capital_requirement = 0 WHERE working_capital_requirement IS NULL")
    op.execute("UPDATE finance_assessments SET policy_version = '1' WHERE policy_version IS NULL")
    op.execute("UPDATE finance_assessments SET total_interest = 0 WHERE total_interest IS NULL")
    op.execute("UPDATE finance_assessments SET emi = 0 WHERE emi IS NULL")
    op.execute("UPDATE finance_assessments SET capitalized_principal = 0 WHERE capitalized_principal IS NULL")
    op.execute("UPDATE finance_assessments SET active_repayment_months = 0 WHERE active_repayment_months IS NULL")
    op.execute("UPDATE finance_assessments SET total_tenure_months = 0 WHERE total_tenure_months IS NULL")
    op.execute("UPDATE finance_assessments SET annual_interest_rate = 0 WHERE annual_interest_rate IS NULL")
    op.execute("UPDATE finance_assessments SET recommended_loan = 0 WHERE recommended_loan IS NULL")
    op.execute("UPDATE finance_assessments SET maximum_loan = 0 WHERE maximum_loan IS NULL")
    op.execute("UPDATE finance_assessments SET margin_contribution = 0 WHERE margin_contribution IS NULL")
    op.execute("UPDATE finance_assessments SET project_cost = 0 WHERE project_cost IS NULL")
    op.execute("UPDATE decisions SET confidence = 0 WHERE confidence IS NULL")

    op.alter_column('stress_test_scenarios', 'resilience_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_column('stress_test_scenarios', 'break_even_status')
    op.alter_column('stress_test_scenarios', 'break_even',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'working_capital_requirement',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'policy_version',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('finance_assessments', 'total_interest',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'emi',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'capitalized_principal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'active_repayment_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('finance_assessments', 'total_tenure_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('finance_assessments', 'annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'recommended_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'maximum_loan',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'margin_contribution',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('finance_assessments', 'project_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.drop_column('finance_assessments', 'engine_version')
    op.alter_column('evidence', 'raw_reference',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('evidence', 'parent_evidence_ids',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decisions', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    # ### end Alembic commands ###
