"""Phase 2 P0 sync infrastructure

Revision ID: 9f9307fedd66
Revises: 4301e3d279b2
Create Date: 2026-09-22 21:48:37.746736

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f9307fedd66'
down_revision: Union[str, None] = '4301e3d279b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SEQUENCE global_sync_sequence')
    op.create_table('sync_changes',
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_sync_changes_record_id'), 'sync_changes', ['record_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_table_name'), 'sync_changes', ['table_name'], unique=False)
    op.create_index('ix_sync_changes_table_op', 'sync_changes', ['table_name', 'operation'], unique=False)
    op.create_table('sync_requests',
    sa.Column('sync_request_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('sync_request_id')
    )
    op.drop_index('ix_sync_records_client_id', table_name='sync_records')
    op.drop_index('ix_sync_records_entity_id', table_name='sync_records')
    op.drop_index('ix_sync_records_entity_op', table_name='sync_records')
    op.drop_index('ix_sync_records_entity_type', table_name='sync_records')
    op.drop_index('ix_sync_records_payload_hash', table_name='sync_records')
    op.drop_index('ix_sync_records_server_time', table_name='sync_records')
    op.drop_index('ix_sync_records_server_timestamp', table_name='sync_records')
    op.drop_table('sync_records')
    op.add_column('business_assumptions', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_business_assumptions_server_revision'), 'business_assumptions', ['server_revision'], unique=False)
    op.add_column('businesses', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_businesses_server_revision'), 'businesses', ['server_revision'], unique=False)
    op.add_column('decisions', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_decisions_server_revision'), 'decisions', ['server_revision'], unique=False)
    op.add_column('evidence', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_evidence_server_revision'), 'evidence', ['server_revision'], unique=False)
    op.add_column('finance_assessments', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_finance_assessments_server_revision'), 'finance_assessments', ['server_revision'], unique=False)
    op.add_column('locations', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_locations_server_revision'), 'locations', ['server_revision'], unique=False)
    op.add_column('market_data', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_market_data_server_revision'), 'market_data', ['server_revision'], unique=False)
    op.add_column('pilot_results', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_pilot_results_server_revision'), 'pilot_results', ['server_revision'], unique=False)
    op.add_column('pilots', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_pilots_server_revision'), 'pilots', ['server_revision'], unique=False)
    op.add_column('scheme_rules', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_scheme_rules_server_revision'), 'scheme_rules', ['server_revision'], unique=False)
    op.add_column('schemes', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.drop_constraint('schemes_scheme_name_key', 'schemes', type_='unique')
    op.drop_index('ix_schemes_scheme_name', table_name='schemes')
    op.create_index(op.f('ix_schemes_scheme_name'), 'schemes', ['scheme_name'], unique=True)
    op.create_index(op.f('ix_schemes_server_revision'), 'schemes', ['server_revision'], unique=False)
    op.add_column('stress_test_scenarios', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_stress_test_scenarios_server_revision'), 'stress_test_scenarios', ['server_revision'], unique=False)
    op.add_column('stress_tests', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_stress_tests_server_revision'), 'stress_tests', ['server_revision'], unique=False)
    op.add_column('users', sa.Column('server_revision', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_users_server_revision'), 'users', ['server_revision'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_server_revision'), table_name='users')
    op.drop_column('users', 'server_revision')
    op.drop_index(op.f('ix_stress_tests_server_revision'), table_name='stress_tests')
    op.drop_column('stress_tests', 'server_revision')
    op.drop_index(op.f('ix_stress_test_scenarios_server_revision'), table_name='stress_test_scenarios')
    op.drop_column('stress_test_scenarios', 'server_revision')
    op.drop_index(op.f('ix_schemes_server_revision'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_name'), table_name='schemes')
    op.create_index('ix_schemes_scheme_name', 'schemes', ['scheme_name'], unique=False)
    op.create_unique_constraint('schemes_scheme_name_key', 'schemes', ['scheme_name'])
    op.drop_column('schemes', 'server_revision')
    op.drop_index(op.f('ix_scheme_rules_server_revision'), table_name='scheme_rules')
    op.drop_column('scheme_rules', 'server_revision')
    op.drop_index(op.f('ix_pilots_server_revision'), table_name='pilots')
    op.drop_column('pilots', 'server_revision')
    op.drop_index(op.f('ix_pilot_results_server_revision'), table_name='pilot_results')
    op.drop_column('pilot_results', 'server_revision')
    op.drop_index(op.f('ix_market_data_server_revision'), table_name='market_data')
    op.drop_column('market_data', 'server_revision')
    op.drop_index(op.f('ix_locations_server_revision'), table_name='locations')
    op.drop_column('locations', 'server_revision')
    op.drop_index(op.f('ix_finance_assessments_server_revision'), table_name='finance_assessments')
    op.drop_column('finance_assessments', 'server_revision')
    op.drop_index(op.f('ix_evidence_server_revision'), table_name='evidence')
    op.drop_column('evidence', 'server_revision')
    op.drop_index(op.f('ix_decisions_server_revision'), table_name='decisions')
    op.drop_column('decisions', 'server_revision')
    op.drop_index(op.f('ix_businesses_server_revision'), table_name='businesses')
    op.drop_column('businesses', 'server_revision')
    op.drop_index(op.f('ix_business_assumptions_server_revision'), table_name='business_assumptions')
    op.drop_column('business_assumptions', 'server_revision')
    op.create_table('sync_records',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('client_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('server_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sync_records_pkey')
    )
    op.create_index('ix_sync_records_server_timestamp', 'sync_records', ['server_timestamp'], unique=False)
    op.create_index('ix_sync_records_server_time', 'sync_records', ['server_timestamp'], unique=False)
    op.create_index('ix_sync_records_payload_hash', 'sync_records', ['payload_hash'], unique=False)
    op.create_index('ix_sync_records_entity_type', 'sync_records', ['entity_type'], unique=False)
    op.create_index('ix_sync_records_entity_op', 'sync_records', ['entity_type', 'entity_id', 'operation'], unique=False)
    op.create_index('ix_sync_records_entity_id', 'sync_records', ['entity_id'], unique=False)
    op.create_index('ix_sync_records_client_id', 'sync_records', ['client_id'], unique=False)
    op.drop_table('sync_requests')
    op.drop_index('ix_sync_changes_table_op', table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_table_name'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_record_id'), table_name='sync_changes')
    op.drop_table('sync_changes')
    op.execute('DROP SEQUENCE global_sync_sequence')
    # ### end Alembic commands ###
